### ISSUE TITLE
Error finding savegame directory

### ISSUE THREAD

**Issue by aggalex** [bartzaalberg/sudokular#13]
Bug appeared on a freshly installed app from appcenter.
Obviously the app/installer forgot to create the `savegame` file.
After creating the file, things worked properly.

```
[INFO 21:04:46.802364] Application.vala:155: com.github.bartzaalberg.sudokular version: (null)
[INFO 21:04:46.802466] Application.vala:157: Kernel version: 4.15.0-54-generic
[ERROR 21:04:46.900192] SudokuSettings.vala:69: Error opening file /home/alex/.local/share/com.github.bartzaalberg.sudokular/savegame: No such file or directory
Trace/breakpoint trap
```

**Comment by unbelievableflavour** [comment]
Did you try the master build? This was actually fixed. I will release a new version soon.
https://github.com/bartzaalberg/sudokular/pull/9

**Comment by aggalex** [comment]
Oh ok. Looks like Mr. Nakano is faster than me. Keep up the good work, @bartzaalberg and @ryonakano!
