### ISSUE TITLE
Change colors when using dark theme

### ISSUE THREAD

**Issue by NathanBnm** [bartzaalberg/sudokular#5]
Maybe you should make the Sudoku grid white, and change the numbers color when using dark theme: 

![image](https://user-images.githubusercontent.com/45366162/60757131-ea243480-a006-11e9-9543-87d20060a918.png)

You should adjust the header image too:

![image](https://user-images.githubusercontent.com/45366162/60757118-d1b41a00-a006-11e9-86f7-45f491939fa3.png)

**Comment by unbelievableflavour** [comment]
Will do!

**Comment by unbelievableflavour** [comment]
Done, added to next release.

**Comment by unbelievableflavour** [comment]
Released. Closing this.
