### ISSUE TITLE
Add an option to quit or reset game

### ISSUE THREAD

**Issue by NathanBnm** [bartzaalberg/sudokular#6]
It would be great to have the possibility to go back to the home screen (with a confirmation dialog) or to reload a new game directly in a current game.

Maybe you can add the possibility to change directly the difficulty during the game (with a confirmation that inform the user that the current game will be lost).

What do you think?

**Comment by unbelievableflavour** [comment]
Yeah I noticed I wanted to go quit and go back the menu while ingame. I'm already creating that. Will give you a heads up when it's released. 

About difficulty: That should be a separate issue. But I think a different puzzle is loaded if difficulty changes. I will have look at that too.

**Comment by unbelievableflavour** [comment]
Done, added to next release. I added a nice difficulty change screen when selected new game

**Comment by unbelievableflavour** [comment]
Released. Closing this.
